services:
  - type: web
    name: sc-content-generator-front
    buildCommand: npm install && npm run build
    staticPublishPath: /dist
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
    routes:
      - type: rewrite
        source: /*
        destination: /index.html