services:
  - type: web
    name: sc-content-generator-front
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    headers:
      /**:
        - name: Cache-Control
          value: no-store
    routes:
      - type: rewrite
        source: /*
        destination: /index.html